### ISSUE TITLE
ERROR Plugin load failed: hexo-tag-bootstrap

### ISSUE THREAD

**Issue by lijunW** [Ares-X/hexo-theme-freemind.bithack#2]
~/Git/wanglijunBlog/wanglijunBlog(master*) » hexo new page about
ERROR Plugin load failed: hexo-tag-bootstrap
/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/hexo-tag-bootstrap/input.js:8
<div class="form-group">
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/hexo-tag-bootstrap/index.js:14:23
    at /Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/wanglijun/Git/wanglijunBlog/wanglijunBlog/node_modules/bluebird/js/release/nodeback.js:42:21
INFO  Created: ~/Git/wanglijunBlog/wanglijunBlog/source/about/index.md

**Comment by Ares-X** [comment]
把 hexo-tag-bootstrap卸载试试呢，不影响渲染

**Comment by Riskerchan** [comment]
解决方法已经出来了，在CSDN上看到了。。。使用hexo+gitee搭建博客时踩的小坑（Plugin load failed: %s hexo-tag-bootstrap）https://blog.csdn.net/qq_39740562/article/details/110228981
