### ISSUE TITLE
Hexo generate fails due some function

### ISSUE THREAD

**Issue by rodhnnya** [Ares-X/hexo-theme-freemind.bithack#5]
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 174 ms
ERROR TypeError: C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\index.ejs:5
    3| </div>
    4|
 >> 5| <%- partial('_partial/index', {index: true}) %>
    6|

C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\_partial\index.ejs:16
    14|                 <% page.posts.each(function(item){ %>
    15|                         <%- partial('post/title', {item: item, index: index}) %>
 >> 16|                         <%- partial('post/entry', {item: item, index: index}) %>
    17|                 <% }); %>
    18|
    19|                 </div>

C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\_partial\post\entry.ejs:12
    10|                 </div>
    11|         <% } %>
 >> 12|         <% if (item.excerpt && index) { %>
    13|                 <%- item.excerpt %>
    14|         <% } else if (theme.auto_excerpt.enable) { %>
    15|

Cannot read property 'enable' of undefined
    at eval (C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\_partial\post\entry.ejs:50:38)
    at entry (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\_partial\index.ejs:30:17)
    at _Query.forEach (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\warehouse\lib\query.js:36:7)
    at eval (C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\_partial\index.ejs:24:19)
    at index (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\Users\dummy\Documents\blog\leblog.github.io\themes\freemind.bithack\layout\index.ejs:19:17)
    at index (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\dummy\Documents\blog\leblog.github.io\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12) {
  path: 'C:\\Users\\dummy\\Documents\\blog\\leblog.github.io\\themes\\freemind.bithack\\layout\\index.ejs'
}
INFO  0 files generated in 45 ms

**Comment by Ares-X** [comment]
try
```
npm install hexo-excerpt --save
```

**Comment by rodhnnya** [comment]
Same thing, wondering if it's related to hexo version, can't recall which other version tried and got a different output tho. 

edit: currently using hexo 5.4.0

**Comment by tlcyqj2023** [comment]
Hey I had the same problem, the solution was to add in the theme file.
`
auto_excerpt:
    enable: true
    lines: 50
`

**Comment by tlcyqj2023** [comment]
https://i.imgur.com/azoXHyi.png

**Comment by rodhnnya** [comment]
Awesome, running the `npm install hexo-excerpt --save` after editing the value @FxckA mentioned worked like a charm. 
Thanks all.

**Comment by thearchivalone** [comment]
Even though this is closed, another solution if you don't want to directly edit the theme (in case you run it as a git submodule and the creator updates it at some point), in the root directory, you can create a `_config.<insert-what-you-saved-the-theme-as>.yml` and add the lines there too. Any custom theme configs there with that naming convention are evaluated before the main theme's. :D

This fix definitely helped me out quite a bit. Thanks. <3
